"""empty message

Revision ID: d71775adb219
Revises: 
Create Date: 2022-02-26 18:30:29.310314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71775adb219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipt', sa.Column('dateofrecipt2', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipt', 'dateofrecipt2')
    # ### end Alembic commands ###
